### ISSUE TITLE
Initial evaluation of challenge 4

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#132]
Add challenge 4 to the repository and set up a simple test run.

**Comment by travitch** [comment]
Some initial impressions from our meeting:
- The recursion in `choose_new_sa` might be a problem for the exploration/alignment phase. There is some code to detect cycles, but we need to test to make sure that it will work as we expect with this direct recursion
- We might want to mark recursion in the proof structure to denote a place where soundness might be compromised (until we have a solid story for fixedpoints)
- One line patch: It seems like this should just work
- Iterative patch: It seems very unlikely we can say anything constructive here. We will probably be able to say that it is different
- Recursive patch: This seems likely to just work also (the path conditions differ, which should yield a useful conditional equivalence)
  - We will likely need to provide some metadata to match up the slices, given that we are adding an extra exit to one of them (and the automated matching will not align them because the postconditions are inconsistent). Our existing metadata is close to being able to do this already, and we just need to extend it now that we have a use case
  - It will probably need to short-circuit the case totality check
  - We may eventually want to generate a more clever totality check that properly accounts for the difference

**Comment by danmatichuk** [comment]
Here is the relevant line from the conditional equivalence check, where it tries to see if the goal verification condition is satisfiable:

https://github.com/GaloisInc/pate/blob/376d9867c68a69e6ec10e44e54147bc50a0785d7/src/Pate/Verification.hs#L822

**Comment by danmatichuk** [comment]
This is potentially explained by issue #151
