### ISSUE TITLE
Initial evaluation of challenge 5

### ISSUE THREAD

**Issue by danmatichuk** [GaloisInc/pate#133]
Add challenge 5 to the repository and set up a simple test run.

**Comment by travitch** [comment]
- We will need to model `malloc` calls; currently they are treated as any other call in a way that is sufficiently abstract that it might not be useful
  - This is actually a bit tricky because our handling of calls (i.e., excluding them from slices) actually happens at the level of slice creation
  - To work around this, we probably want to pass in a custom callback to the slice creation that takes a function call as an input and returns either Nothing (current behavior - exclude) or Just a symbolic expression representing them. For `malloc`, that could be a fresh array
  - This feature will also likely be necessary for the differential inlining work
- There is no patch provided (but the description is precise enough to work with easily)
- We don't currently have any logic for propagating differences backwards, so we don't have a way to talk about the two encryption functions precisely
- The specification we *want* to have is that the encryption functions don't modify any memory that isn't passed to them (i.e., they are different but don't break anything else)
- The likely best approach is to add an argument that describes the two functions as equivalent (and modifying their final argument). This could be thought of as a generalization of the ExternalDomain infrastructure, where an input could tell us precisely what to say about the two different functions

**Comment by danmatichuk** [comment]
The main change that is required here is for the verifier to be able to "discover" areas of memory that it decides it is allowed to not require to be equivalent. By default, the verifier tries to prove equivalence of all memory after the main entry point function "returns", but this is not strictly required. So there are two steps here:

* Add an additional hint category where functions can be specified to yield relaxed post-domains. This is likely just saying that, for example, the first argument to the function represents X bytes of memory that are considered "inconsequential"

* When traversing the call stack from the top, if we encounter any function call that is in the hint database above, we modify the requested postcondition to exclude any inconsequential addresses.

* The resulting top-level condition will therefore not necessarily be the one that was originally requested for verification, since it may now include a collection of inconsequential addresses which have been explicitly ignored by the verifier.
