### ISSUE TITLE
Enhance the memory model to store symbolic regions

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#24]
Our pointer abstraction represents symbolic pointers as a pair of two symbolic values: a region identifier and an offset into that region. Memory allocations are each assigned a unique region identifier.   Both components can be symbolic.  Currently, we do not record region numbers when we write pointers to memory.  This means that reading them back produces fully symbolic pointers (i.e., with an unconstrained region number), which is overly pessimistic in many cases.

There are multiple solutions to the problem:
- Retain the region ID representation and add one or two extra symbolic arrays to explicitly track the (possibly symbolic) region ID (and a "dirty" bit for each entry, indicating whether or not a written pointer has been unsafely sliced in a way we can't reason about)
- Modify the pointer representation to no longer have an explicit pointer region, but instead merely have predicates separating the possible pointer cases. Note that this might be a huge lift left to future work, as it would require moving from the LLVMPointer type to something else

**Comment by danmatichuk** [comment]
Currently we assume that all read values from memory are plain bitvectors (i.e. a pointer with a zero region). See here:

https://github.com/GaloisInc/pate/blob/418755109d55e8e0d7cc8a830abfe9495e426af0/src/Pate/Memory/MemTrace.hs#L725

This is a soundness issue that will be a problem for any programs which manipulate pointers. Returning an arbitrary (fully-symbolic) region will currently break the equality checks, because any value read from memory will necessarily have a different region between the original and patched programs. This also presents an issue for pre-domain propagation, since we rely on distinguishing stack pointers and global memory pointers (by considering the stack as a distinguished memory region).

It shouldn't be too difficult to fix the memory model to retain this region information. However we may have issues during verification due to the initial memory states being almost entirely symbolic for most problems. This will likely require some additional infrastructure for passing around side conditions about memory - which could also be useful for retaining information about pointer aliasing.

**Comment by travitch** [comment]
Tagging @dmwit since he'll be taking a look at this

**Comment by danmatichuk** [comment]
Currently to account for this weakness we are assuming that all pointer-values registers have region zero initially at the start of each block slice. Noting here that once the memory model is upgraded to support regions we will need to weaken this assumption to instead assume that these regions are initially symbolic.

**Comment by danmatichuk** [comment]
This will require some changes to the verifier interface, outlined in #136

**Comment by thebendavis** [comment]
completed
