### ISSUE TITLE
Frame data structure documentation

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#66]
A few questions about data types around the frame computation. If you answer here, I can update the haddocks.

# `StatePred`

What is the meaning of these fields?  Guesses:

- `predRegs`: the predicate must be true of the register associated with it when the slice starts executing
- `predStack`: the `MemPred` must hold over the stack when the slice starts executing
- `predMem`: the `MemPred` must hold over the rest of memory when the slice starts executing

Is the `StatePred` effectively the entire precondition?

# `MemPred`

How should the locations be interpreted (aside from the polarity)?  What does the `NatRepr` represent? Is it an offset?  Is it the pointer width?

- In `MemCells`, the `Pred` must (or must not) hold for the given cell?
- `MemCell` also has a `NatRepr` with the same width - is this duplicate information?  Is it just for convenience?

# `EquivRelation`

How does the `EquivRelation` relate to the `StatePred`?  Is it just a matter of data vs code (i.e., the `EquivRelation` is a collection of functions that generate predicates).

# Reporting frames

Which type is the most suitable for reporting a frame?  I was thinking that the `StatePred` generated in `guessEquivalenceDomain` could easily be bundled into the `ComputedPrecondition` event.

**Comment by danmatichuk** [comment]
# `StatePred` vs `EquivRelation`

A `StatePred` represents a symbolic set of locations, used to define either a pre-domain or a post-domain. It's called a `StatePred` simply because I was originally thinking of its representation as a predicate: i.e. `{location}` ~ `location -> bool`. The `Pred`  in the range of these maps (in both `regPred` and `MemCells` in `memPredLocs`) is the predicate  that defines whether or not a specific location belongs to the given `StatePred`.

An `EquivRelation` defines an equivalence relation that holds between two program states. Abstractly it can be thought as `location -> state Original -> state Patched -> bool`.  Currently there is only one equivalence relation that is defined, which simply reads the relevant location from each state and returns a predicate indicating if the resulting values are exactly equivalent.

An equivalence problem is a combination of an `EquivRelation` which is guarded by a `StatePred` that defines its domain. Specifically, the following statement represents either an assumption or a proof goal for an equivalence problem: given `e : EquivRelation` and `d : StatePred` we say the states `stO` and `stP` are equivalent with respect to `e` and `d` if `forall loc: location. d(loc) --> e(loc, stO, stP)`. That is, the `EquivRelation` is only assumed, or proven, to hold on the locations defined by `StatePred`.

The way that this formula is represented concretely as a `What4.Pred` is different depending on whether or not it is meant to be *assumed* as a precondition, or *proven* as a postcondition (i.e. via `Equivalence.statePredPre` or `Equivalence.statePredPost`). This is necessary to handle the quantification over all locations.

# `MemPred`

In `MemPred`, the polarity changes whether or not the predicate is inclusive or exclusive of the given set of `MemCells` inside of it. So we say that an address satisfies (or is contained within) a positive `MemPred` if it is equal to one of its entries, or it satisfies a negative `MemPred` if it is not equal to any of its entries.

A `MemPred` defines a set of addresses. Combined with an equivalence relation, a positive predicate defines the set of addresses that are either assumed, or must be proven to be equivalent, while a negative predicate defines the set of addresses that either cannot be assumed, or may be neglected to be proven equivalent.

A `MemCell` represents a number of addresses equal to its `w` parameter. The `NatRepr` represents the number of bytes that the cell spans. That is, a `MemCell sym arch 1` with a `cellPtr` of `0x00000001` represents exactly that address, while `MemCell sym arch 4` with the same `cellPtr` represents the addresses spanning `0x00000001` to `0x00000004`. Reading from a `MemCell` has the following signature: 
`MemCell sym arch w -> LLVMPtr sym (8 * w)` (see `MemCell.readMemCell`)

The `NatRepr` is redundantly stored inside the `MemCell` so that we know how many bytes to read given only a `MemCell`. Its also stored in the domain of `MemPred.memPredLocs` so that we can check whether or not a given `MemCell` belongs to the `MemPred`.

It's worth noting that the address range `0x00000001` to `0x00000004` could be represented in multiple ways with different `MemCell` widths, but the translation into the underlying concrete memory model is insensitive to this when considering the equivalence of their *contents*.

# Reporting frames

The `StatePred` from `guessEquivalenceDomain` certainly makes the most sense. However I'm in the process of writing a more abstract representation of the frame that will likely be better suited for reporting as part of the proof object rework.
